services:
  - type: web
    name: mpbenti
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install
      npm run build
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: mpbenti-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@mpbenti.com.au"
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true

databases:
  - name: mpbenti-db
    databaseName: mpbenti
    user: mpbenti