# Generated by Django 5.0.7 on 2025-11-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='abn',
            field=models.CharField(blank=True, help_text='Australian Business Number (11 digits)', max_length=11, verbose_name='ABN'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_address',
            field=models.TextField(blank=True, help_text='Full business address (street, city, state, postcode)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_name',
            field=models.CharField(default='MP Benti', help_text='Legal business name for invoices', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_phone',
            field=models.CharField(blank=True, help_text='Business contact phone number', max_length=50),
        ),
    ]
