# Generated by Django 5.0.7 on 2025-09-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_load_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
