# Generated by Django 5.0.7 on 2025-09-23 13:11 - Modified to run after pack_size increase

import os
import json
from django.db import migrations
from django.core.management import call_command
from django.contrib.auth import get_user_model
from django.conf import settings


def load_initial_data(apps, schema_editor):
    """Load initial fixtures and create superuser if database is empty."""

    # Check if we already have data (avoid loading twice)
    Category = apps.get_model('catalogue', 'Category')
    User = get_user_model()

    if Category.objects.exists():
        print("Data already exists, skipping initial data load.")
        return

    # Load fixtures from the JSON file
    fixture_path = os.path.join(settings.BASE_DIR, 'initial_data.json')
    if os.path.exists(fixture_path):
        print("Loading initial data fixtures...")
        call_command('loaddata', fixture_path, verbosity=2)
    else:
        print("Warning: initial_data.json not found, skipping fixture load.")

    # Create superuser if none exists and we have environment variables
    if not User.objects.filter(is_superuser=True).exists():
        username = os.environ.get('DJANGO_SUPERUSER_USERNAME')
        email = os.environ.get('DJANGO_SUPERUSER_EMAIL')
        password = os.environ.get('DJANGO_SUPERUSER_PASSWORD')

        if username and email and password:
            print(f"Creating superuser: {username}")
            User.objects.create_superuser(
                username=username,
                email=email,
                password=password
            )
            print("Superuser created successfully.")
        else:
            print("Warning: Superuser environment variables not set, skipping superuser creation.")
    else:
        print("Superuser already exists, skipping creation.")


def reverse_load_initial_data(apps, schema_editor):
    """Reverse migration - remove the loaded data."""
    # Note: This is optional and can be dangerous in production
    # For safety, we'll just pass and let manual cleanup handle this
    print("Reverse migration: Manual cleanup of initial data may be required.")
    pass


class Migration(migrations.Migration):
    atomic = False  # Disable atomic transactions for fixture loading

    dependencies = [
        ('catalogue', '0006_increase_pack_size_length'),  # Must run after pack_size is increased
        ('dashboard', '0001_initial'),  # Ensure dashboard models exist
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_load_initial_data),
    ]
