# Generated by Django 5.0.7 on 2026-07-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_replace_unit_fields_with_pack_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack_description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
