# Generated by Django 5.0.7 on 2026-08-11 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_product_pack_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
