# Generated by Django 5.0.7 on 2025-11-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text='Customer delivery/billing address (street, city, state, postcode)'),
        ),
    ]
