# Generated by Django 5.0.7 on 2025-11-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Date invoice was generated', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Auto-generated invoice number (e.g., INV-2025-00001)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='unit_price_ex_gst',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit excluding GST at time of order', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='unit_price_inc_gst',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit including GST at time of order', max_digits=10, null=True),
        ),
    ]
